# Generated by Django 4.2.11 on 2024-04-13 14:02

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='directory',
            field=models.FileField(upload_to=pages.models.get_upload_path),
        ),
    ]
